export const GET_ERRORS = "APP_GET_ERRORS";
export const SET_CURRENT_USER = "APP_SET_CURRENT_USER";
export const SET_INIT_STATE = "APP_SET_INIT_STATE";
export const GET_ALL_PRODUCTS = "APP_GET_ALL_PRODUCTS";
export const SET_USER_PRODUCTS = "APP_SET_USER_PRODUCTS";
export const SET_PRODUCT = "APP_SET_PRODUCT";
